### PR TITLE
Move the chemistry tool examples in the user docs to Jupyter examples

### PR DESCRIPTION
**Pull request by SShilo**
Background
Improvements have been made to Stoichiometry Calculations.rst and Thermochemistry Calcuations.rst. These improvements include the changing the code from static .rst to a more dynamic .ipynb. Minor challenges have been met, but progress has been made.

Purpose
To upgrade the Stoichiometry Calculations.rst and Thermochemistry Calcuations.rst files into .ipynb file.

Approach
Anaconda 3.5 was downloaded and jupyter was used to create the file attached. Most of the .rst file was changed into either Markdown, Headings or code to allow interaction.
Where technical limitations were met they were displayed as comments(especially putting a markdown between the code and the expected outcomes)

Notes: The structure of the file can be improved by allowing sphinx to do its work of styling the markdown and headings, but the pip install in anaconda did not help.
         : An install of auxi needs to be made in the anaconda environment.

### CODE REVIEW

**Comment by SShilo** [comment]
ISSUES 118 and 119. The examples will follow.

**Comment by christoffkok** [comment]
Hi Simon,

Thank you very much!

These 2 new Jupyter notebooks should exist the src/example/tools/chemistry folder (the chemistry folder should be created.).

Will you name then stoichiometry_calculations and thermochemistry_calculations?

Our file naming conventions aren't documented. I will add an issue for this.

**Comment by christoffkok** [comment]
Hi Simon,

I changed the name of the issue to: "Move the chemistry tool examples in the user docs to Jupyter examples"

I also created a new branch for you on Ex-Mente/auxi.0 against which you can submit a pull request.
Will you fix those issues and submit a pull request against the `issue-140` branch?

Kind Regards,
Christoff

**Comment by christoffkok** [comment]
We will add your changes to next week's auxi release.

**Comment by johanzietsman-em** [comment]
You addressed both issues 118 and 119 in this pull request. You may only address a single issue per pull request.

**Pull request closed without merging**
